pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "10.27.0.2": ["bismuth.arkanosis.net:4242"]
  "10.27.0.12": ["192.168.0.12:4242"]
  "10.27.0.13": ["192.168.0.13:4242"]
  "10.27.0.14": ["192.168.0.14:4242"]
  "10.27.0.16": ["192.168.0.16:4242"]
  "10.27.0.18": ["192.168.0.18:4242"]
  "10.27.0.19": ["192.168.0.19:4242"]
  "10.27.0.20": ["192.168.0.20:4242"]
  "10.27.0.28": ["192.168.0.28:4242"]
  "10.27.0.31": ["192.168.0.31:4242"]
  "10.27.0.32": ["192.168.0.32:4242"]
  "10.27.0.40": ["192.168.0.40:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts: # lighthouse hosts this node should report to and query from (SHOULD BE EMPTY ON LIGHTHOUSE NODES)
    - "10.27.0.2"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

cipher: chachapoly

preferred_ranges: ["192.168.0.0/24"]

tun:
  # When tun is disabled, a lighthouse can be started without a local tun interface (and therefore without root)
  disabled: false
  dev: nebula0
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: 22
      proto: tcp
      group: desktop

    - port: 22
      proto: tcp
      group: laptop
