#! /bin/bash

IF=$(ip a | sed -n 's/^[0-9]\+: \(w[a-z0-9]\+\): .*/\1/p')

CONFIG="/etc/wpa_supplicant/wpa_supplicant-$IF.conf"

offline 2> /dev/null

ip link set "$IF" up && \
    if [ $# -eq 0 ]; then
        wpa_supplicant -B -m '' -i "$IF" -c "$CONFIG"
    else
        if ! grep -q '^ *ssid="'"$1"'"$' "$CONFIG"; then
            echo "SSID $1 not found in $CONFIG" >&2
            exit 1
        fi
        wpa_supplicant -B -m '' -i "$IF" -c <(awk '
            BEGIN {
                keep = 0
            }
            /^ *ssid="'"$1"'"$/ {
                print "network={"
                keep = 1
            }
            {
                if (keep) {
                    print
                }
            }
            /^}$/ {
                keep = 0
            }
        ' "$CONFIG")
    fi && \
    dhcpcd "$IF" && \
    iw "$IF" link
