#! /bin/bash

IF=$(ip a | sed -n 's/^[0-9]\+: \(w[a-z0-9]\+\): .*/\1/p')

offline 2> /dev/null

ip link set "$IF" up && \
    if [ $# -eq 0 ]; then
        wpa_supplicant -B -m '' -i "$IF" -c "/etc/wpa_supplicant/$IF.conf"
    else
        if ! grep -q '^ *ssid="'"$1"'"$' "/etc/wpa_supplicant/$IF.conf"; then
            echo "SSID $1 not found in /etc/wpa_supplicant/$IF.conf" >&2
            exit 1
        fi
        wpa_supplicant -B -m '' -i "$IF" -c <(awk '
            BEGIN {
                keep = 0
            }
            /^ *ssid="'"$1"'"$/ {
                print "network={"
                keep = 1
            }
            {
                if (keep) {
                    print
                }
            }
            /^}$/ {
                keep = 0
            }
        ' "/etc/wpa_supplicant/$IF.conf")
    fi && \
    dhcpcd "$IF" && \
    iw "$IF" link
