# "-*- sh -*-"

pushd `dirname $0` >&-

source ./postconf
source ./paths

source ./abbrev
source ./alias
source ./arc
source ./backup
source ./bookmarks
source ./cd
source ./cp
source ./color
source ./compile
source ./completion
source ./conf
source ./dist
source ./duplicates
source ./dot
source ./files
source ./firefox
source ./hash
source ./history
source ./keys
source ./less
source ./ln
source ./ls
source ./math
source ./mkdir
source ./mv
source ./mute
source ./options
source ./prefix
source ./prompt
source ./proxy
source ./rm
source ./run
source ./quota
source ./search
source ./ssh
source ./stats
#source ./stderr
source ./truecrypt
source ./usb
source ./vcs
source ./watch
source ./zle

popd