# "-*- sh -*-"

pushd $0:h > /dev/null

source postconf
source arch
source paths
source compat
source editor

source abbrev
source alias
source arc
source backup
source bookmarks
source cd
source cp
source color
source compile
source completion
source conf
source dot
source files
source firefox
source highlight
source history
source keys
source less
source ln
source ls
source math
source mkdir
#source monitor
source mv
source network
source options
source paste
source prefix
source prompt
source proxy
source rm
source run
source quota
source search
source stats
#source stderr
source synergy
source truecrypt
source watch
source zle

popd > /dev/null
