#! /bin/sh

cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 ssh://borgbackup@localhost:2222/home/borgbackup/backups/bismuth/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S) \
	 ./ \
	 --exclude=boot \
	 --exclude=dev \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp
