#! /bin/sh

echo 'Backing up /mnt, please make sure that nothing apart form /mnt/hdd is being mounted there'

sleep 10

START="$(date)"
DRIVE="Gymir"

cd && \
    mount.ecryptfs_private Sauvegardes && \
    cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 "/run/media/arkanosis/$DRIVE/borgbackup/$(hostname)/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S)" \
	 ./ \
	 --exclude=boot \
	 --exclude=dev \
	 --exclude=home/.ecryptfs \
	 --exclude=home/arkanosis/.cache \
	 --exclude=home/nonfreegaming/.cache \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt/hdd/.Sauvegardes \
	 --exclude=mnt/hdd/Téléchargements/Distributions \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp \
	 --exclude=var/cache/pacman/pkg &&
    {
        echo "Start: $START"
        echo "End: $(date)"
        echo "Host: $(hostname)"
        echo "Drive: $DRIVE"
    } | mail -Sttycharset=utf8 -s "Sauvegarde de $(hostname) sur $DRIVE effectuée avec succès" arkanosis@gmail.com
