#! /bin/sh

cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 /run/media/arkanosis/Gymir/borgbackup/Edelweiss/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S) \
	 ./ \
	 --exclude=boot \
	 --exclude=dev \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt/ssd/boot \
	 --exclude=mnt/ssd/dev \
	 --exclude=mnt/ssd/lost+found \
	 --exclude=mnt/ssd/media \
	 --exclude=mnt/ssd/mnt \
	 --exclude=mnt/ssd/proc \
	 --exclude=mnt/ssd/run \
	 --exclude=mnt/ssd/sys \
	 --exclude=mnt/ssd/tmp \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp \
	 --exclude=var/cache/pacman/pkg
