#! /bin/sh

cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 ssh://borgbackup@localhost:2214/run/media/arkanosis/Gymir/borgbackup/Cyclamen/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S) \
	 ./ \
	 --exclude=boot \
	 --exclude=cdrom \
	 --exclude=dev \
	 --exclude=home/arkanosis/.cache \
	 --exclude=home/Annette/.cache \
	 --exclude=home/Daniel/.cache \
	 --exclude=home/Sandrine/.cache \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt/hdd \
	 --exclude=mnt/hdd2/lost+found \
	 --exclude=mnt/Heimdal \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp
