#! /bin/sh

cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 /run/media/arkanosis/Gymir/borgbackup/marvin/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S) \
	 ./ \
	 --exclude=boot \
	 --exclude=dev \
	 --exclude=home/.ecryptfs \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp \
	 --exclude=var/cache/pacman/pkg
