#! /bin/sh

# hadduck backup
# (C) 2021-2022 Jérémie Roquet <jroquet@arkanosis.net>
# Released under the ISC license

set -e

VERSION='v0.1.0'

usage() {
    echo 'Usage: hadduck <drive>'
}

if [ $# -eq 0 ] || [ "x$1" = 'x-h' ] || [ "x$1" = 'x--help' ]; then
    usage
    exit 0
elif [ "x$1" = 'x--version' ]; then
    echo "hadduck $VERSION"
    exit 0
elif [ $# -ne 1 ]; then
    usage >&2
    exit 1
fi

START="$(date)"
HOST="$(hostname)"
OS="$(sed -n 's/^ID=//p' /etc/os-release)"
DRIVE="$(echo "$1" | sed 's/@.*//')"
REMOTE="$(echo "$1" | sed -n 's/[^@]*@\([^@]\+\)\?$/\1/p')"
BACKUP="${HOST}_$(date +%Y-%m-%d-%H-%M-%S)"

if [ "x$DRIVE" = 'xGymir' ] || [ "x$DRIVE" = 'xNjord' ] || [ "x$DRIVE" = 'xVaruna' ]; then
    BACKEND='borg'
elif [ "x$DRIVE" = 'xSusanoo' ]; then
    BACKEND='restic'
elif [ "x$DRIVE" = 'xNeptune' ] || [ "x$DRIVE" = 'xPoseidon' ] || [ "x$DRIVE" = 'xTyphon' ] || [ "x$DRIVE" = 'xAegir' ]; then
    BACKEND='rsnapshot'
else
    echo "Unknown drive '$DRIVE', exiting" >&2
    exit 1
fi

if [ -z "$REMOTE" ]; then
    if [ "x$OS" = 'xarch' ]; then
        TARGET="/run/media/arkanosis/$DRIVE"
    elif [ "x$OS" = 'xdebian' ] || [ "x$OS" = 'xubuntu' ]; then
        TARGET="/media/arkanosis/$DRIVE"
    else
        echo "Unknown OS '$OS', exiting" >&2
        exit 1
    fi

    if ! [ -d "$TARGET" ]; then
        echo "'$TARGET' is not mounted, exiting" >&2
        exit 1
    fi
else
    if [ "x$HOST" = 'xCyclamen' ]; then
        PORT=2214
    elif [ "x$HOST" = 'xMimosa' ]; then
        PORT=2228
    elif [ "x$HOST" = 'xbismuth' ]; then
        PORT=2222
    else
        echo "Host '$HOST' not supported for remote backup"
    fi
    TARGET="ssh://borgbackup@localhost:$PORT/run/media/arkanosis/$DRIVE"
fi

if [ "x$BACKEND" = 'xborg' ]; then
    TARGET="$TARGET/borgbackup/$HOST/"
elif [ "x$BACKEND" = 'xrestic' ]; then
    TARGET="$TARGET/resticbackup/$HOST/"
    echo "Unsupported backend '$BACKEND', exiting" >&2
    exit 1
else
    echo "Unsupported backend '$BACKEND', exiting" >&2
    exit 1
fi

if [ "x$HOST" = 'xgossamer' ]; then
    for username in 'arkanosis' 'nonfreegaming'; do
        if ! [ -d "/home/$username/.local" ]; then
            echo "'/home/$username' is not decrypted, exiting" >&2
            exit 1
        fi
    done
    if ! [ -d '/mnt/hdd' ]; then
        echo "'/mnt/hdd' is not mounted, exiting" >&2
        exit 1
    fi
    for directory in /mnt/*; do
        if [ "x$directory" != 'x/mnt/hdd' ]; then
            echo "Unexpected directory '$directory', exiting" >&2
            exit 1
        fi
    done

    cd && \
        mount.ecryptfs_private Sauvegardes && \
        cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "$TARGET::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=dev \
             --exclude=home/.ecryptfs \
             --exclude=home/arkanosis/.cache \
             --exclude=home/arkanosis/.cargo/registry \
             --exclude=home/nonfreegaming/.cache \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt/hdd/.games \
             --exclude=mnt/hdd/.Sauvegardes \
             --exclude=mnt/hdd/Téléchargements/Distributions \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp \
             --exclude=var/cache/pacman/pkg

    # TODO exclude ~/Programation/*/target
elif [ "x$HOST" = 'xmarvin' ]; then
    cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "$TARGET::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=dev \
             --exclude=home/.ecryptfs \
             --exclude=home/arkanosis/.cache \
             --exclude=home/arkanosis/.cargo/registry \
             --exclude=home/arkanosis/Téléchargements/Distributions \
             --exclude=home/nonfreegaming/.cache \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp \
             --exclude=var/cache/pacman/pkg
elif [ "x$HOST" = 'xEdelweiss' ]; then
    cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "$TARGET::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=dev \
             --exclude=home/arkanosis/.cache \
             --exclude=home/arkanosis/.cargo/registry \
             --exclude=home/arkanosis/Téléchargements/Distributions \
             --exclude=home/nonfreegaming/.cache \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt/ssd/boot \
             --exclude=mnt/ssd/dev \
             --exclude=mnt/ssd/home/arkanosis/.cache \
             --exclude=mnt/ssd/home/arkanosis/.cargo/registry \
             --exclude=mnt/ssd/home/arkanosis/Téléchargements/Distributions \
             --exclude=mnt/ssd/lost+found \
             --exclude=mnt/ssd/media \
             --exclude=mnt/ssd/mnt \
             --exclude=mnt/ssd/proc \
             --exclude=mnt/ssd/run \
             --exclude=mnt/ssd/sys \
             --exclude=mnt/ssd/tmp \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp \
             --exclude=var/cache/pacman/pkg
elif [ "x$HOST" = 'xtaz' ] || [ "x$HOST" = 'xMimosa' ]; then
    cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "$TARGET::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=cdrom \
             --exclude=dev \
             --exclude=home/.ecryptfs \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp
elif [ "x$HOST" = 'xCyclamen' ]; then
    cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "$TARGET::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=cdrom \
             --exclude=dev \
             --exclude=home/arkanosis/.cache \
             --exclude=home/arkanosis/.cargo/registry \
             --exclude=home/Annette/.cache \
             --exclude=home/Daniel/.cache \
             --exclude=home/Sandrine/.cache \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt/hdd \
             --exclude=mnt/hdd2/lost+found \
             --exclude=mnt/Heimdal \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp
elif [ "x$HOST" = 'xbismuth' ]; then
    cd / && \
        sudo borg create \
             --stats \
             --progress \
             --compress lz4 \
             "ssh://borgbackup@localhost:$PORT/home/borgbackup/backups/$HOST/::$BACKUP" \
             ./ \
             --exclude=boot \
             --exclude=dev \
             --exclude=lost+found \
             --exclude=media \
             --exclude=mnt \
             --exclude=proc \
             --exclude=run \
             --exclude=sys \
             --exclude=tmp
else
    echo "Unknown host '$HOST' to backup" >&2
    exit 1
fi

(
    echo "Start: $START"
    echo "End: $(date)"
    echo "Host: $HOST"
    echo "Drive: $DRIVE"
    echo "Backend: $BACKEND"
) | mail -Sttycharset=utf8 -s "Sauvegarde de $HOST sur $DRIVE effectuée avec succès" arkanosis@gmail.com

echo 'Backup finished'

if [ -f '/etc/smartd.conf' ]; then
    echo 'Checking SMART…'
    sudo sed -i 's/@[^ ]\+$/& -M test/' '/etc/smartd.conf'
    sudo systemctl restart smartd.service
    sudo sed -i 's/ -M test$//' '/etc/smartd.conf'
    echo 'Emails should have been sent for:'
    cut -d ' ' -f 1 '/etc/smartd.conf'

    # TODO run a SMART test now?
else
    echo 'SMART not checked'
fi

# TODO run a fstrim now (but only *after* unmounting the backup filesystem!)
#echo 'Running fstrim…'
#sudo systemctl start fstrim
