#! /bin/sh

START="$(date)"

cd / && \
    sudo borg create \
         --stats \
         --progress \
         --compress lz4 \
         "/run/media/arkanosis/Gymir/borgbackup/$(hostname)/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S)" \
         ./ \
         --exclude=boot \
         --exclude=dev \
         --exclude=home/arkanosis/.cache \
         --exclude=home/arkanosis/Téléchargements/Distributions \
         --exclude=home/nonfreegaming/.cache \
         --exclude=lost+found \
         --exclude=media \
         --exclude=mnt/ssd/boot \
         --exclude=mnt/ssd/dev \
         --exclude=mnt/ssd/home/arkanosis/.cache \
         --exclude=mnt/ssd/home/arkanosis/Téléchargements/Distributions \
         --exclude=mnt/ssd/lost+found \
         --exclude=mnt/ssd/media \
         --exclude=mnt/ssd/mnt \
         --exclude=mnt/ssd/proc \
         --exclude=mnt/ssd/run \
         --exclude=mnt/ssd/sys \
         --exclude=mnt/ssd/tmp \
         --exclude=proc \
         --exclude=run \
         --exclude=sys \
         --exclude=tmp \
         --exclude=var/cache/pacman/pkg &&
    {
        echo "Start: $START"
        echo "End: $(date)"
        echo "Host: $(hostname)"
        echo "Drive: Gymir"
    } | mail -Sttycharset=utf8 -s "Sauvegarde de $(hostname) sur Gymir effectuée avec succès" arkanosis@gmail.com
