#! /bin/sh

cd / && \
    sudo borg create \
	 --stats \
	 --progress \
	 --compress lz4 \
	 ssh://localhost:2228/run/media/arkanosis/Njord/borgbackup/Mimosa/::$(hostname)_$(date +%Y-%m-%d-%H-%M-%S) \
	 ./ \
	 --exclude=boot \
	 --exclude=cdrom \
	 --exclude=dev \
	 --exclude=lost+found \
	 --exclude=media \
	 --exclude=mnt \
	 --exclude=proc \
	 --exclude=run \
	 --exclude=sys \
	 --exclude=tmp
