#! /usr/bin/zsh

gif=false

if [[ $# -ge 1 && $1 = -gif ]]; then
    gif=true
    shift
fi

if [ $# -ne 1 ]; then
    echo "Usage: $(basename $0) [-gif] <output.webm>" >&2
    exit 1
fi

geometry=$(xrectsel "-s %wx%h -i :0+%x,%y") || exit 1

if $gif; then
    avconv -f x11grab -show_region 1 -framerate 30 $=geometry # TODO FIXME all arguments + conversion from temp .avi to .gif
else
    avconv -f x11grab -show_region 1 -framerate 30 $=geometry -vcodec libx264 -preset ultrafast -crf 0 -threads 0 $1.mkv
    avconv -i $1.mkv -b:v 5000000 -minrate 200000 -maxrate 40000000 -threads 0 $1
    rm $1.mkv
fi
